//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gradution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camp
    {
        public int id_camp { get; set; }
        public string name_c { get; set; }
        public string majer_c { get; set; }
        public string place_c { get; set; }
        public int count_c { get; set; }
        public System.DateTime date_start_c { get; set; }
        public System.DateTime date_finish_c { get; set; }
        public string comment_c { get; set; }
        public string oCID { get; set; }
    
        public virtual Organizer_party Organizer_party { get; set; }
    }
}
