//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gradution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int id_game { get; set; }
        public string name_g { get; set; }
        public string majer_g { get; set; }
        public int count_g { get; set; }
        public System.DateTime date_start_g { get; set; }
        public System.DateTime date_finish_g { get; set; }
        public string place_g { get; set; }
        public string comment_g { get; set; }
        public string oCID { get; set; }
    
        public virtual Organizer_party Organizer_party { get; set; }
    }
}
