//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gradution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graduate
    {
        public int id_grad { get; set; }
        public string codemeli { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string fathername { get; set; }
        public System.DateTime birth { get; set; }
        public string shnumber { get; set; }
        public string status { get; set; }
        public string phon { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public string study { get; set; }
        public string majer { get; set; }
        public decimal gpa { get; set; }
        public byte[] pic { get; set; }
        public string oCID { get; set; }
    }
}
