//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gradution
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoiningCamp
    {
        public int id_join_camp { get; set; }
        public int CaID { get; set; }
        public int GID { get; set; }
    }
}
