//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gradution
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class School : DbContext
    {
        public School()
            : base("name=School")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Camp> Camps { get; set; }
        public virtual DbSet<ChairmanMeeting> ChairmanMeetings { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Graduate> Graduates { get; set; }
        public virtual DbSet<JoiningCamp> JoiningCamps { get; set; }
        public virtual DbSet<JoiningGame> JoiningGames { get; set; }
        public virtual DbSet<JoiningMeeting> JoiningMeetings { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<Oganizer> Oganizers { get; set; }
        public virtual DbSet<Organizer_party> Organizer_parties { get; set; }
        public virtual DbSet<RequestCamp> RequestCamps { get; set; }
        public virtual DbSet<RequestCompetition> RequestCompetitions { get; set; }
        public virtual DbSet<RequestMeeting> RequestMeetings { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
